#!/usr/bin/env bash
# this scripts will  tells the tale of the file /etc/passwd
while IFS=':' read -ra line; do # this will set : as IFS, read file and split it into array
	# this will echo message with lines inside
    echo "The user ${line[0]} is part of the ${line[3]} gang, lives in ${line[5]} and rides ${line[6]}. ${line[2]}'s place is protected by the passcode ${line[1]}, more info about the user here: ${line[4]}"
# then insert the file
done < /etc/passwd 
