#!/usr/bin/env bash
# scripts that summarizes HTTP status code occurrences pf each IP from a log file using awk.

awk '{print $1,$9}' apache-access.log | sort -V | uniq -c | sort -n | perl -e 'print reverse <>'
