#!/usr/bin/env bash
# scripts that displays numbers from 1 to 20 and luck messages at certain time
counter=1
while [ $counter -lt 21 ]; do # while counter is less than 20, do ...
    echo $counter # this will display the numbers
    case "$counter" in
        "4")
            echo "bad luck from China"
            ;;
        "9")
            echo "bad luck from Japan"
            ;;
        "17")
            echo "bad luck from Italy"
            ;;
    esac
    (( counter+=1 )) # counter updater
done
