#!/usr/bin/env bash
#bash script that displays To infinity and beyond indefinitely

# this counter is for while loop
counter=2
while [ $counter -gt 0 ]; do
    echo "To infinity and beyond"
    sleep 2
done
